### ISSUE TITLE
No component factory found for Ng2DatetimePickerComponent

### ISSUE THREAD

**Issue by bruno-serfe** [ng2-ui/ng2-datetime-picker#115]
Hi guys,

Someone can tell me something about this error? I think is related to this: https://github.com/angular/angular/issues/10735

Any idea of how to fix?

zone.js:1102 Uncaught TypeError: Cannot create property 'configurable' on string 'Error: No component factory found for Ng2DatetimePickerComponent
    at NoComponentFactoryError.Error (native)
    at NoComponentFactoryError.BaseError [as constructor] (http://192.168.33.10:3000/vendor.bundle.js:6582:34)
    at new NoComponentFactoryError (http://192.168.33.10:3000/vendor.bundle.js:27155:16)

**Comment by allenhwkim** [comment]
Please create a plunker example to reproduce this error

**Comment by allenhwkim** [comment]
Closing for inactivity and out of scope.
